deploy-job-production:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SRV_HOST_IO > ~/.ssh/known_hosts
  script:
    - DATE_TIME=$(date +%Y%m%d%H%M)
    - ssh -o StrictHostKeyChecking=no -T $SRV_USER_IO@$SRV_HOST_IO "cd /var/repos/aydym-lang-analyzer && git fetch origin && git reset --hard origin/master && docker build -t docker.tapgo.biz:6666/tmcars-repo/aydym-lang-ai-prod:$DATE_TIME . && docker push docker.tapgo.biz:6666/tmcars-repo/aydym-lang-ai-prod:$DATE_TIME"
    - ssh -o StrictHostKeyChecking=no -T $SRV_USER_AI_OFFICE@$SRV_HOST_AI_OFFICE "cd /opt/lang_analyzer && docker-compose down && sed -i 's|docker.tapgo.biz:6666/tmcars-repo/aydym-lang-ai-prod:.*|docker.tapgo.biz:6666/tmcars-repo/aydym-lang-ai-prod:$DATE_TIME|' docker-compose.yml && docker-compose up -d"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /root/.cache/pip
  only:
    - master